namespace Connector.Endpoints.v1.Image;

using Json.Schema.Generation;
using System;
using System.Text.Json.Serialization;
using Xchange.Connector.SDK.CacheWriter;

/// <summary>
/// Represents an image generated by OpenAI's API
/// </summary>
[PrimaryKey("id", nameof(Id))]
//[AlternateKey("alt-key-id", nameof(CompanyId), nameof(EquipmentNumber))]
[Description("Represents an image generated by OpenAI's API")]
public class ImageDataObject
{
    [JsonPropertyName("id")]
    [Description("The unique identifier for the image")]
    [Required]
    public required string Id { get; init; }

    [JsonPropertyName("url")]
    [Description("The URL of the generated image")]
    public string? Url { get; init; }

    [JsonPropertyName("b64_json")]
    [Description("The base64-encoded JSON of the generated image")]
    public string? B64Json { get; init; }

    [JsonPropertyName("revised_prompt")]
    [Description("The prompt that was used to generate the image, if there was any revision")]
    public string? RevisedPrompt { get; init; }

    [JsonPropertyName("created_at")]
    [Description("The Unix timestamp (in seconds) for when the image was created")]
    [Required]
    public required long CreatedAt { get; init; }
}